name: flux-ci
description: Flux-CI is your own lightweight CI server.
license: MIT
url: 'https://github.com/NiklasRosenstein/flux-ci'

requirements:
  - Flask>=0.10.1
  - pony>=0.7.3
  - pyOpenSSL>=0.15.1
  - cryptography>=2.0
  - nr.fs<=1.5.0,<1.6.0
  - nr.types>=4.0.0,<5.0.0
  - requests

package_data:
  - flux/server/static/**
  - flux/server/templates/**
